# Generated by Django 3.2.9 on 2021-12-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
        ),
    ]
