# Generated by Django 3.2.9 on 2021-12-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_publication_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
        ),
    ]
