# Generated by Django 4.2.4 on 2023-08-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_user_account_type_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FREE'), (2, 'PRO')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'user')]),
        ),
    ]
