# Generated by Django 4.2.4 on 2023-08-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_user_account_type_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FREE'), (2, 'PRO')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'user')], default=1),
        ),
    ]
